### ISSUE TITLE
Cheats don't work in school world.

### ISSUE THREAD

**Issue by Naxanria** [Sunekaer/academy-testing#102]
* **Modpack Version**: Beta 7

* **Issue**: When in the school world, I accidentally used the upgrade kit to upgrade the cell ( #101 ). So tried to give myself a new one. But it told me i did not have permission whiel teh world is in cheat mode.

![image](https://user-images.githubusercontent.com/3246224/61292217-eb0c5180-a7d0-11e9-931f-5a2b253dc683.png)

![image](https://user-images.githubusercontent.com/3246224/61292226-efd10580-a7d0-11e9-8a0b-2ab1274fbe46.png)

Opening to lan with enabling cheats also did not work. Nor opening to lan and selecting creative mode, as it just keeps you in survival mode.

* **Is it Repeatable?**: Yes.

**Comment by Sunekaer** [comment]
Worlds created with cheat enable I can fine go in creative mode

**Comment by Sunekaer** [comment]
But yes most commands and cheat stuff is disable in school, but creative works that I know because I used it last night
