### ISSUE TITLE
[SUGGESTION] Change scaling for quest bookmarks

### ISSUE THREAD

**Issue by Naxanria** [Sunekaer/academy-testing#103]
## Context	
Scaling of quest bookmarks in the default GUI Scale (for this pack: Normal(2)) makes it really small, almost not readable.

![image](https://user-images.githubusercontent.com/3246224/61292613-03c93700-a7d2-11e9-9514-347feea65916.png)

**Comment by Sunekaer** [comment]
FTB quest issue
