### ISSUE TITLE
Visual path to follow

### ISSUE THREAD

**Issue by deividaslord** [Sunekaer/academy-testing#109]
I feel like there should be some more visual information, like arrows or something that indicates, when you need to move to the next room.

**Comment by aaronhowser1** [comment]
Hmm, if banners could be horizontal we could have arrows along the floor once a room is completed. @LatvianModder

**Comment by aaronhowser1** [comment]
![](https://cdn.discordapp.com/attachments/552245600721174528/606294692811898883/unknown.png)
Arrows are set to gamestages, which are given/removed by quests
