### ISSUE TITLE
[SUGGESTION] Add quest for Slime Channels

### ISSUE THREAD

**Issue by Slyklaw** [Sunekaer/academy-testing#11]
To go along with the Drop of Evil, you need a good way to move mobs to a killzone. Tinker's Slime Channels appear to be the only way, so a quest pointing these out would help players. They don't hinder mob spawning or Cursed Earth spreading.

**Comment by aaronhowser1** [comment]
Good idea! Added
![image](https://user-images.githubusercontent.com/15698722/56811981-970c5500-67ff-11e9-9d3c-a2ac465ed786.png)
