### ISSUE TITLE
fluidpumps

### ISSUE THREAD

**Issue by deividaslord** [Sunekaer/academy-testing#120]
Fluid pumps from industrial foregoing are bugged. They seem like the only useful pumps in the game atm.

If you insert range addon after it has gotten power and has sucked the lava it could, it wont work. And then the pump gets bugged
Than if you replace the pump, it wont take any power from nearby source (as dynamos and fluxduct).
With other words, i do not now how to get it working again, after its bugged.

![2019-07-29_18 17 53](https://user-images.githubusercontent.com/24681210/62064473-342abf80-b22d-11e9-9aaa-84418c981653.png)

![2019-07-29_18 02 42](https://user-images.githubusercontent.com/24681210/62064437-22e1b300-b22d-11e9-8050-5253ba8c4956.png)

**Comment by Sunekaer** [comment]
not a bug, it thinks it's done.
You need to put the addon first and then power it.

**Comment by aaronhowser1** [comment]
Very strange behavior though. We've talked to Buuz about this before and
confirmed it's intended behavior. It stops checking for lava once it's
pumped everything in thr work area, even if the work area changes.
