### ISSUE TITLE
[SUGGESTION] CraftPresence change to have Academy logo

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#122]

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/62228525-1b054880-b3be-11e9-8c8b-a1c7f775223f.png)
fixed

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/62248613-2781a500-b3ae-11e9-949e-4938ee5fda91.png)
Unless you just havent pushed it yet

**Comment by Sunekaer** [comment]
Haven’t pushed forgot to lol
