### ISSUE TITLE
[SUGGESTION] Change default font to minecraft font

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#123]
SmoothFont doesnt just add fonts, it changes the vanilla font to scale better.
![image](https://user-images.githubusercontent.com/15698722/62185257-543ea980-b327-11e9-9a84-a1b6ed191483.png)
Modded veterans dislike new fonts, so I doubt newbies would appreciate it very much.

Also every time I post a screenshot to the modded mc discord people yell at me for using verdana font :(

**Comment by Sunekaer** [comment]
I know that it does and no its staying, if they don’t want it they can remove the mod
