### ISSUE TITLE
[SUGGESTION] Mojang's logo on the loading screen

### ISSUE THREAD

**Issue by MrGREGhimself** [Sunekaer/academy-testing#124]
Mojang's logo on the loading screen looks like someone just slapped the blue half-transparent background on top of it.

My suggestion is purely cosmetic and it is to make it (if possible) so it looks like Mojang's original logo (red) with black text).

**Comment by Sunekaer** [comment]
Well to fix that i need to change the background back to white..

**Comment by aaronhowser1** [comment]
What mod is it that lets us tint the load screen? Maybe we could make an issue there to change it to like

- Remove the logo
- Tint the background
- Put the logo back in, so it stays the normal color

**Comment by Sunekaer** [comment]
That would be forge

**Comment by Sunekaer** [comment]
Fixed in dev
