### ISSUE TITLE
[SUGGESTION] Toggle Colored Light Shaders to OFF

### ISSUE THREAD

**Issue by MrGREGhimself** [Sunekaer/academy-testing#125]
For people that never played with mods or even Optifine, the mechanic that the Colored Light Shaders from p455w0rd's Library brings will most likely make them feel like something is off as the effect is quite strong and inconsistent. 
For example:
Placed torch gives yellowish tint, but dropped torch tint effect looks 3 times stronger.

My suggestion is to set it to OFF by default.

**Comment by aaronhowser1** [comment]
The whole mod is gone in Beta 8, because Dank Null is dead (for now)

**Comment by Sunekaer** [comment]
Like Aaron said mod is being removed
