### ISSUE TITLE
Sawdust in Pulverizer (JEI)

### ISSUE THREAD

**Issue by MrGREGhimself** [Sunekaer/academy-testing#127]
* **Modpack Version**: FTB Academy BETA7

* **Issue**: When checking how to make **Sawdust** (thermalfoundation:material - Metadata:800) there are Pulverizer processing recipes that suggest you get it from nothing.
There are 4 blank recipes in total.

* **Screenshot**: [Link](http://mrgreghimself.com/ftb_academy/Sawdust.png)
* **Is it Repeatable?**: Yes

* **Mod/s Affected**: JEI

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/62195070-ce2f5c80-b340-11e9-9ae6-1b5bdcec6ce3.png)
Extremely strange. If only **Thermal Expansion hadn't closed their freaking issue tracker so we could report it argh**
We might be able to craft tweak it away, like remove all recipes for sawdust and then add back the ones that aren't broken or something.

**Comment by Sunekaer** [comment]
Cant fix this.. i need "inputStack" for removing pulverizer recipes... and "null" is not valid and its not minecraft air
