### ISSUE TITLE
[SUGGESTION] Remove fluxduct from inventory after placing energy cell

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#133]

**Comment by Sunekaer** [comment]
No

**Comment by aaronhowser1** [comment]
Why not? It just stays in your inventory until you leave the room

**Comment by Sunekaer** [comment]
Because if you pick up 2 ducts and place the cell you’ll be missing on duct, so therefor I’m waiting with removal until they are 100% with that quest line

**Comment by aaronhowser1** [comment]
Ah yeah that's fair

**Comment by aaronhowser1** [comment]
Although if you break a duct, you can't place it back down can you?
Adventure mode and all

**Comment by Sunekaer** [comment]
You can, we had that coded in FTBAM, so it get the tag applied on pickup

**Comment by Sunekaer** [comment]
Same with the energy cell
