### ISSUE TITLE
[SUGGESTION] Tutorial for reset/skip buttons

### ISSUE THREAD

**Issue by Sunekaer** [Sunekaer/academy-testing#137]
update tutorial to tell about reset and skip button
https://s1.sunekaer.com/i/01-08-2019_19-14-00_Discord.png

**Comment by aaronhowser1** [comment]
The first tutorial is a Quest tutorial, so it doesn't really fit there. I could make a second tutorial that's a command reward for finishing the first quest though, like how the JEI tutorial pops up after its quest

**Comment by aaronhowser1** [comment]
I think it should say it in chat instead, taking control and opening the tutorial would be a bit too much.

Plus, if I don't put it in the tutorial list (from the tutorial inventory button), they can only see it once. If it's in chat, they just have to open chat.
If I *do* put it in the tutorial list, it'd be there even after they leave the school, even though the commands can only be done in the school (I think).

**Comment by aaronhowser1** [comment]
Oh I didn't even notice the buttons at all

**Comment by Sunekaer** [comment]
they are new

**Comment by Sunekaer** [comment]
We can have lat hide them outside school

**Comment by aaronhowser1** [comment]
They aren't in the tutorial list, but theres a command for it as a reward for the first quest
