### ISSUE TITLE
[SUGGESTION] Add XL Food Mod

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#14]
Never used the mod, but it looks fine and it would be nice to have a food mod.

https://minecraft.curseforge.com/projects/xl-food-mod

**Comment by Sunekaer** [comment]
Mod added in dev, assigned to aaronhowser1

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/56817500-561a3d80-680b-11e9-9271-fbd50e40c760.png)
