### ISSUE TITLE
Making a wishlist of items :)

### ISSUE THREAD

**Issue by deividaslord** [Sunekaer/academy-testing#141]
As i can see there is only obsidian thats wither proof, right? I feel like we need more, since im already want to farm withers, but cant really do it safely.

**Comment by deividaslord** [comment]
And maybe a trashcan, bin, voidsomething filter or idk. I get allot of useless items from mobfarms, And need to through stone swords and etc out

**Comment by aaronhowser1** [comment]
Obsidian isn't Wither-proof. However, I think Withers can't break blocks in claimed chunks

**Comment by aaronhowser1** [comment]
The Nullifier destroys all items and fluids piped into it

**Comment by Sunekaer** [comment]
Where wont be added anymore mods.
