### ISSUE TITLE
End dragon bugged

### ISSUE THREAD

**Issue by deividaslord** [Sunekaer/academy-testing#143]
unloaded chunks, came back, accidently broke one end crystal all exploded and this happend. I tried to replace crystals, but it did not help

![image](https://user-images.githubusercontent.com/24681210/62427843-7c4c5500-b6f9-11e9-8a1a-817e591c5cd9.png)

**Comment by deividaslord** [comment]
As i read it happens it vannilla as well some times. could be simple an minecraft issue again.. Just close it if it is

**Comment by Sunekaer** [comment]
I havent heard this should be an issue before, try and summon it again and see
