### ISSUE TITLE
[SUGGESTION] JourneyMap tutorial?

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#147]
Maybe place it as a command reward for the first Overworld quest?

**Comment by Sunekaer** [comment]
Because overworld isn’t a “safe” place then it definitely shouldn’t be auto claim on it

**Comment by aaronhowser1** [comment]
Right, makes sense. Did we not do the thing with setting it to day if nobody else is on (or in SP)?

**Comment by Sunekaer** [comment]
Yes but still MP and people afk

**Comment by Sunekaer** [comment]
Make the reward so they have to click it
