### ISSUE TITLE
Used dynamos don't complete the quest.

### ISSUE THREAD

**Issue by Slyklaw** [Sunekaer/academy-testing#15]
If you place a dynamo and pick it up, before completing the RTFM quest, then the dynamo quests won't recognize the dynamo in your inventory. You must complete the RTFM quest first, then craft a fresh dynamo to finish the dynamo quests.

**Comment by aaronhowser1** [comment]
Are you sure you can't click on the task or throw it down and pick it back up again? It's an item detect task, not a crafting task.

**Comment by Slyklaw** [comment]
I suspect it has something to do with cheating in items in creative mode. Normal playthrough works fine. I'll close for now and re-open if I find a repro case without cheating.
