### ISSUE TITLE
Endoflame banner doesn't show up at the right time, and Wand banners appear too early

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#155]
![image](https://user-images.githubusercontent.com/15698722/63072958-02cc1800-beec-11e9-96c2-01db4598dda3.png)

**Comment by aaronhowser1** [comment]
This is right after making the Endoflame. There should be a banner for it on the left, and the wands shouldn't appear until it's placed and Moving and Storing Mana has started

**Comment by Sunekaer** [comment]
fixed
