### ISSUE TITLE
[SUGGESTION] Add Open Blocks/Drop Of Evil

### ISSUE THREAD

**Issue by TangoCheetahs** [Sunekaer/academy-testing#156]
## Context		
The Drop[ of Evil is mentioned in current quests but is not implemented in the pack yet. In the Mob_Utils Conveyor quest, It says these conveyors are great for drop of evil spawners, but the drop of evil is not in the pack. I would recommend changing the quest or adding the drop of evil to give an example. OpenBlocks also adds some other "useful" (opinionated) blocks and items, but I am more focused on the quest/drop of evil.

## Mod Details	
* Name:	OpenBlocks
* CurseForge Link: https://www.curseforge.com/minecraft/mc-mods/openblocks

**Comment by Sunekaer** [comment]
There wont be added anymore mods.

**Comment by Sunekaer** [comment]
Which quest is the drop of evil mentioned in? @aaronhowser1 need to remove that

**Comment by aaronhowser1** [comment]
It was in the TiCon Slime Channel quest, changed to just say it's good in mob grinders in general.
