### ISSUE TITLE
Ender Tank/Chest quests refer to Private and Personal interchangeably.

### ISSUE THREAD

**Issue by Slyklaw** [Sunekaer/academy-testing#2]
Stick with either Private or Personal to avoid confusion.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/56658063-40681500-665f-11e9-808c-da15534afd6c.png)
![image](https://user-images.githubusercontent.com/15698722/56658125-6a213c00-665f-11e9-8753-c429dab949f5.png)
As a side note, should I rephrase it so it doesn't say "thing"?
