### ISSUE TITLE
[SUGGESTION] Slight change to ores quest from Getting Started chapter

### ISSUE THREAD

**Issue by loneztar** [Sunekaer/academy-testing#24]
Completion requirement for Thaumcraft ores says it needs Nether Quartz (which is vanilla) and there is no requirement for Amber (which is Thaumcraft).  possibly switch ?

**Comment by aaronhowser1** [comment]
I have Quartz because of the Quartz Ore added by TC, but I'll add Amber

**Comment by aaronhowser1** [comment]
Added Amber
