### ISSUE TITLE
[SUGGESTION] Add some mod that allows mob farming

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#27]
Maybe [Mob Grinding Utils](https://minecraft.curseforge.com/projects/mob-grinding-utils)? [Industrial Forgoing](https://minecraft.curseforge.com/projects/industrial-foregoing) would also work, but it does a lot more than just mob farming (although that's worth looking into too, right now we have to use the Phytogenic Insolator for all our farming).

**Comment by Slyklaw** [comment]
Thermal's Creature Encaptulator and Centrifugal Separator work pretty well, but there are a couple of mob types that get stuck in it.

EU2 spikes are already available and work great. Add in Dark Utilities for the vector plates and ender tether and you've got a great farm.
