### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by loneztar** [Sunekaer/academy-testing#28]
Are there any plans to add a farming mod such as Forestry to automate (at least) vanilla food production ? There's also Progressive Automation for something a little simpler.		
 ## Mod Details		
 * Name:	Progressive Automation / Forestry	
 * CurseForge Link: 
https://minecraft.curseforge.com/projects/progressive-automation-early-miner

     https://minecraft.curseforge.com/projects/forestry

**Comment by Sunekaer** [comment]
Progressive Automation yes 
Forestry no

**Comment by Sunekaer** [comment]
Progressive Automation added in Dev, needs quest and guide made
