### ISSUE TITLE
Quests lang keys wrong/not correct

### ISSUE THREAD

**Issue by Sunekaer** [Sunekaer/academy-testing#30]
![image](https://user-images.githubusercontent.com/18720460/57526496-d4a7cc80-732d-11e9-8fba-5f583841ef68.png)
![image](https://user-images.githubusercontent.com/18720460/57526533-e38e7f00-732d-11e9-9cd2-5416fb51233c.png)
![image](https://user-images.githubusercontent.com/18720460/57526579-10429680-732e-11e9-808b-b6669610f64f.png)
![image](https://user-images.githubusercontent.com/18720460/57526639-31a38280-732e-11e9-84b5-e96f038d2f7a.png)
![image](https://user-images.githubusercontent.com/18720460/57526695-5c8dd680-732e-11e9-88ba-13794a9c33c9.png)

**Comment by aaronhowser1** [comment]
Fixed in dev
