### ISSUE TITLE
academy.relay.text text typo 

### ISSUE THREAD

**Issue by drcrazy** [Sunekaer/academy-testing#31]
1. academy.relay.text 
Relays act as Cables but the connection is severed when a Redstone signal is applied.

Should it be "served"?

I mean I haven't tested by myself. If it requires redstone signal to work or to not work. Or behaviour could be changed using GUI.

2. academy.detector.text

The Detector will emit a Redstone signal when the sytem has more, exactly, or less than a specified amount of a specified item or fluid.

"syStem"

**Comment by aaronhowser1** [comment]
As for the first, it should be "severed." When it is given a Redstone signal, the connection is cut and stops working until the signal is removed.

Fixed typo in the second
