### ISSUE TITLE
[SUGGESTION] Information for brand new modded MC players

### ISSUE THREAD

**Issue by MrGREGhimself** [Sunekaer/academy-testing#33]
Brand new modded MC or even new MC players in general might not know how long it takes to gather materials/ores from mining to be able to progress through the quests in the pack if the rewards were not available. It could be a good idea to indicate that in reward descriptions by explaining how long would that process take.

**Comment by Sunekaer** [comment]
@aaronhowser1 what you think?

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/57633202-cb567400-7568-11e9-85f5-fb5f21858c10.png)
Here's what I had to say about it
