### ISSUE TITLE
[SUGGESTION] Final chapter

### ISSUE THREAD

**Issue by MrGREGhimself** [Sunekaer/academy-testing#34]
Teaching people on how to play modded is one thing, but giving them a choice at the end to find their own favourite style of play is completely different.

Final chapter could point/showcase other styles of play by showcasing the best things about other packs (FTB).
Maybe using Compact Machines or RFTools Dimensions could bring player to basics of the packs like:
Stoneblock, Sky Odyssey or even Interactions

**Comment by MrGREGhimself** [comment]
In general putting people in "scenarios" would allow them to learn better how packs work.

**Comment by Sunekaer** [comment]
Good suggestion, but no we are only gonna try and teach people the basic, so they can jump in to other packs/play styles without it being a big scary amount of things they dont know.
also you dont find your favorite play style from just a small preview you need to try them, maybe multiple times, what we can do is write in the guide a bit about some of the different types of packs and give som names on some of them, @aaronhowser1 and i have talked about doing that, dont know if he already have done it

**Comment by aaronhowser1** [comment]
I haven't yet, but I probably will at some point

**Comment by aaronhowser1** [comment]
Any references to other packs would probably be in the Misc section of the Guide, and not in quests. I theoretically like the idea of having little demos for other packs, but adding mods for that would be a bit much I think.
