### ISSUE TITLE
[SUGGESTION] Add small fun mods

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#40]
Discussed here: https://discordapp.com/channels/369881656930205698/552245600721174528/579415392682770479

Stuff like Portalgun or Trumpet Skeletons etc, small things that show off how fun modded minecraft is

**Comment by aaronhowser1** [comment]
Also see [this thread](https://www.reddit.com/r/feedthebeast/comments/aicgq9/what_are_your_favorite_small_silly_mods/)

**Comment by aaronhowser1** [comment]
![](https://cdn.discordapp.com/attachments/303440391124942858/579445293787906058/unknown.png)
Add Emojiful so such a tragedy never happens again

**Comment by aaronhowser1** [comment]
[Creepy Confetti](https://minecraft.curseforge.com/projects/creeper-confetti)
[Trumpet Skeleton](https://minecraft.curseforge.com/projects/doot) (and maybe also [Instrumental Mobs](https://minecraft.curseforge.com/projects/instrumental-mobs))
Maybe [Clay Soldiers](https://minecraft.curseforge.com/projects/clay-soldiers-mod)
[Petrock Mod](https://minecraft.curseforge.com/projects/petrock-mod), though we'd want to remove the ore and give it a new recipe I think
[Portal Gun](https://minecraft.curseforge.com/projects/portal-gun)
Maybe [Sinc](https://minecraft.curseforge.com/projects/sync)
Maybe [Morph](https://minecraft.curseforge.com/projects/morph)
[Hats](https://minecraft.curseforge.com/projects/hats)?
[Emojiful](https://minecraft.curseforge.com/projects/emojiful)

**Comment by aaronhowser1** [comment]
Apparently [Metamorph](https://minecraft.curseforge.com/projects/metamorph) also exists, but I dont know what makes it different than Morph. Maybe it has mob abilities that Morph doesn't?

**Comment by Sunekaer** [comment]
added:
Emojiful
Hats
Portal Gun
Creepy Confetti
Instrumental Mobs
