### ISSUE TITLE
Stuff for lat to do

### ISSUE THREAD

**Issue by Sunekaer** [Sunekaer/academy-testing#67]
Detection of when something is written in JEI for the JEI quest
Text task can be used for the TOP Quest

Done

> Detection of Open Iron Chest, open Diamond Chest, open Small Storage Crate, open Large Storage Crate, and maybe Refined storage terminal?
> Observation task can be used for the draw quests/TOP Quest
> Fix quest desync
> Detection of placement for tech/energy

**Comment by Sunekaer** [comment]
Basics chapter isn't auto-selected, because it's not the top chapter even tho others are invisible.
and for some reason, it shows X and Y out of edit mode

**Comment by Sunekaer** [comment]
Tutorial

**Comment by LatvianModder** [comment]
Location Task to use Screens with XYZ+WHD so each area can be detected to trigger quest instead of Click Me button
