### ISSUE TITLE
DE Armor quests

### ISSUE THREAD

**Issue by Sunekaer** [Sunekaer/academy-testing#68]
In Technology - Intermediate 
there 1 quest for all 4 pieces

And in advanced its in 4 different quests

**Comment by aaronhowser1** [comment]
My reasoning for that was that I didn't want to overfill the Intermediate chapter, and each piece of Wyvern armor doesn't have anything special about it. Each Draconic armor piece has something special, like flight or step assist, but Wyvern armor doesn't. Also, I didn't want to have to explain the shield stuff 4 times.
