### ISSUE TITLE
Botania and AS Guide.

### ISSUE THREAD

**Issue by Sunekaer** [Sunekaer/academy-testing#69]
Botania and AS Guide are blank

**Comment by aaronhowser1** [comment]
Maybe instead of being a copy of the books, I could show off how to automate stuff like Endoflames

**Comment by Sunekaer** [comment]
To be honest i think it should just telling them to search in the tome and lexicon, because everything is in there

**Comment by Sunekaer** [comment]
So say that in the first quest of each of them and remove it from the guide
