### ISSUE TITLE
[SUGGESTION] It takes too long to generate Mana in the school

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#73]
It takes *way* too long for a single Endoflame to make enough Mana for one Manasteel Ingot. It's like five minutes of waiting before you can complete that quest. Maybe if it filled up a lot after the mana task is completed?

**Comment by Sunekaer** [comment]
Well, they can just drop in the other pools.
But currently do have a way to set their pool to have more mana, we can add a mana tablet quest where they get a half full tablet that they need to drain?
