### ISSUE TITLE
Crash when right clicking donkey with empty hand.

### ISSUE THREAD

**Issue by Naxanria** [Sunekaer/academy-testing#88]
* **Modpack Version**:  Beta 6.2
* **Issue**: Crash, when right clicking donkey with an empty hand.

* **Link to Log or Crash File Paste**: 
[crash-2019-07-11_18.26.44-client.txt](https://github.com/Sunekaer/academy-testing/files/3383039/crash-2019-07-11_18.26.44-client.txt)

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Seen crash report, its a Quark issue

**Comment by aaronhowser1** [comment]
Report this to Quark too if you haven't already

**Comment by Sunekaer** [comment]
https://github.com/Vazkii/Quark/issues/1383

**Comment by Naxanria** [comment]
They said
> Your log says Quark 166. This bug was fixed in 167.
As Quark is now updated to 168, can close this issue.
