### ISSUE TITLE
Chiseling to polished marble gives wrong output.

### ISSUE THREAD

**Issue by Naxanria** [Sunekaer/academy-testing#89]
* **Modpack Version**: 6.2 Beta

* **Issue**: When chiseling marble to get polished marble from Quark (Bottom right) You get Marble Bricks from Quark instead.
![image](https://user-images.githubusercontent.com/3246224/61073780-6f985200-a416-11e9-953c-49a9d38ed27e.png)

* **Is it Repeatable?**: yes

* **Mod/s Affected**:  Quark/Chisel

**Comment by Sunekaer** [comment]
https://s1.sunekaer.com/i/15-07-2019_21-03-35_javaw.png
Works for me

**Comment by Naxanria** [comment]
Was happening on the server, so might have been because of that. I tested now and in Single and Multi it has been solved. I guess because the update of quark (166->168), that might have addressed this as well.
