### ISSUE TITLE
[SUGGESTION] Change the icon in the first Academy advancement

### ISSUE THREAD

**Issue by aaronhowser1** [Sunekaer/academy-testing#96]
![image](https://user-images.githubusercontent.com/15698722/61260251-09c40700-a743-11e9-8f2f-12d2b25c6e8d.png)
It bugs out the Advancement Tab because it's enchanted. Maybe use the Quest Book item instead, which has the same texture but no glow

**Comment by Sunekaer** [comment]
@LatvianModder Change it to minecraft:book
